In [1]:
import pandas as pd
import numpy as np

#load the data
df = pd.read_csv('../data/raw/retail_sales_raw.csv', encoding='latin-1')

#check the data

print("Shape:", df.shape)

df.head()

Shape: (9994, 21)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [5]:
# check column names and data types
print("\nData Types:")
print(df.dtypes)

#check for missing values
print("\nMissing Values:")  
print(df.isnull().sum())

#check for duplicates
print("\nDuplicate Rows:", df.duplicated().sum())

#basic statistics
df.describe()

Data Types:
Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

Missing Values:
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

Duplicate Rows: 0

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [6]:
#standardizing column names
#Make all column names lowercase and replacing spaces with underscores
df.columns = df.columns.str.lower().str.replace(' ', '_')
print ("Cleaned Column Names:") 
print(df.columns.tolist())

Cleaned Column Names:
['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_id', 'customer_name', 'segment', 'country', 'city', 'state', 'postal_code', 'region', 'product_id', 'category', 'sub-category', 'product_name', 'sales', 'quantity', 'discount', 'profit']

In [7]:
#fix data types
#convert order_date and ship_date to datetime
df['order_date'] = pd.to_datetime(df['order_date'])
df['ship_date'] = pd.to_datetime(df['ship_date'])

#check
print(df[['order_date', 'ship_date']].dtypes)
print(df[['order_date', 'ship_date']].head())

order_date    datetime64[ns]
ship_date     datetime64[ns]
dtype: object
  order_date  ship_date
0 2016-11-08 2016-11-11
1 2016-11-08 2016-11-11
2 2016-06-12 2016-06-16
3 2015-10-11 2015-10-18
4 2015-10-11 2015-10-18

In [8]:
# Check missing values again after type fixes
print("Missing values:\n", df.isnull().sum())

#check for duplicates again after cleaning
print("Duplicate rows:", df.duplicated().sum())

# No missing values or duplicates found, no cleaning needed for these

Missing values:
 row_id           0
order_id         0
order_date       0
ship_date        0
ship_mode        0
customer_id      0
customer_name    0
segment          0
country          0
city             0
state            0
postal_code      0
region           0
product_id       0
category         0
sub-category     0
product_name     0
sales            0
quantity         0
discount         0
profit           0
dtype: int64
Duplicate rows: 0

In [9]:
#Validating Key columns
# Check for negative or zero sales (shouldn't happen)
print("Rows with non-positive sales:", (df['sales'] < 0).sum())

# Check discount range (should be between 0 and 1)
print("Discount range:", df['discount'].min(), "to", df['discount'].max())

# Check unique values in key categorical columns
for col in ['segment', 'category', 'region', 'ship_mode']:
    print(f"\n{col}: {df[col].unique()}")

Rows with non-positive sales: 0
Discount range: 0.0 to 0.8

segment: ['Consumer' 'Corporate' 'Home Office']

category: ['Furniture' 'Office Supplies' 'Technology']

region: ['South' 'West' 'Central' 'East']

ship_mode: ['Second Class' 'Standard Class' 'First Class' 'Same Day']

In [11]:
#save cleaned dataset
df.to_csv('../data/cleaned/cleaned_data.csv', index=False, encoding='utf-8')

print("Cleaned dataset saved!")
df.shape

Cleaned dataset saved!

(9994, 21)

In [12]:
summary = """
DATA CLEANING SUMMARY
=====================
- Loaded raw dataset with {} rows and 21 columns.
- Standardized all column names to lowercase with underscores.
- Converted 'order_date' and 'ship_date' to datetime format.
- Checked for missing values — none found.
- Checked for duplicate rows — none found.
- Validated key columns (sales, discount, categories).
- Final cleaned dataset has {} rows (unchanged).
- Saved as: data/cleaned_data.csv
""".format(df.shape[0], df.shape[0])

print(summary)

# Save as a text file
with open('../data/cleaned/cleaning_summary.txt', 'w') as f:
    f.write(summary)

DATA CLEANING SUMMARY
=====================
- Loaded raw dataset with 9994 rows and 21 columns.
- Standardized all column names to lowercase with underscores.
- Converted 'order_date' and 'ship_date' to datetime format.
- Checked for missing values — none found.
- Checked for duplicate rows — none found.
- Validated key columns (sales, discount, categories).
- Final cleaned dataset has 9994 rows (unchanged).
- Saved as: data/cleaned_data.csv

In [ ]:
cleaned_df= pd.read_csv('data/cleaned_data.csv')
cleaned_df.head()
cleaned_df.dtypes

row_id             int64
order_id          object
order_date        object
ship_date         object
ship_mode         object
customer_id       object
customer_name     object
segment           object
country           object
city              object
state             object
postal_code        int64
region            object
product_id        object
category          object
sub-category      object
product_name      object
sales            float64
quantity           int64
discount         float64
profit           float64
dtype: object

In [ ]:
cleaned_df= pd.read_csv('data/cleaned/cleaned_data.csv')
cleaned_df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub-category,product_name,sales,quantity,discount,profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164